export const apiRoutes = {
  googleLogin: "/users/auth/login?social=google",
  kakaoLogin: "/users/auth/login?social=kakao",
  userLogin: "/users/auth/login",
  userLogout: "/users/auth/logout",
  updateUserName: "/users/nickname",
  updateUserImg: "/users/image",
  deleteUser: "/users",
  main: "/main",
  refrigerator: "/fridges",
  upDateIngredients: "/fridges/ingredients",
  recommendRecipe: "/recipes/recommend",
  showIngredients: "/ingredients",
  recipes: "/recipes",
  recipeCatory: "/recipes/category",
  recipeSearch: "/recipes/search",
  comments: "/comments",
  likes: "/likes",
  bookmarks: "/bookmarks",
  userMypage: "/users/mypage",
  alertsStatus: "/alerts/status",
  alertsEnable: "/users/alerts/enable",
  alerts: "/alerts",
};
